services:
  postgres:
    image: postgres:16-alpine
    container_name: coder-higher-postgres
    environment:
      POSTGRES_DB: coderhigher
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: coder-higher-keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: coderhigher
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KEYCLOAK_ADMIN: root
      KEYCLOAK_ADMIN_PASSWORD: root
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak:/opt/keycloak/data/import

volumes:
  postgres-data:
